---
# vars file for traefik
traefik_config_providers:
  file:
    directory: "{{ traefik_config_dir + '/conf.d/' }}"
    watch: true

traefik_config_entrypoints:
  metrics:
    address: ":9999"
  web:
    address: ":80"
    reuseport: true
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    reuseport: true
    asDefault: true
    http2:
      maxConcurrentStreams: 250
    forwardedHeaders:
      insecure: true

traefik_config_api:
  insecure: "{{ traefik_api_insecure | default(false) }}"
  dashboard: "{{ traefik_api_dashboard | default(true) }}"
  disableDashboardAd: true
