---
# handlers file for alloy
- name: Restart alloy
  ansible.builtin.systemd:
    name: "{{ service_name }}"
    state: restarted
  become: true
  listen: "Restart alloy"

- name: Check alloy is started properly
  ansible.builtin.include_tasks: healthcheck.yml
  listen: "Restart alloy"
