---
- name: Add custom UFW rule
  community.general.ufw:
    comment: "{{ item.comment | default(omit) }}"
    default: "{{ item.default | default(omit) }}"
    policy: "{{ item.policy | default(omit) }}"
    delete: "{{ item.delete | default(false) | boolean }}"
    direction: "{{ item.direction | default(omit) }}"
    from_ip: "{{ item.from_ip | default(omit) }}"
    from: "{{ item.from | default(omit) }}"
    src: "{{ item.src | default(omit) }}"
    from_port: "{{ item.from_port | default(omit) }}"
    insert: "{{ item.insert | default(omit) }}"
    insert_relative_to: "{{ item.insert_relative_to | default('omit') }}"
    interface: "{{ item.interface | default(omit) }}"
    if: "{{ item.if | default(omit) }}"
    log: "{{ item.log | default(omit) }}"
    logging: "{{ item.logging | default(omit) }}"
    name: "{{ item.name | default(omit) }}"
    app: "{{ item.app | default(omit) }}"
    proto: "{{ item.proto | default(omit) }}"
    protocol: "{{ item.protocol | default(omit) }}"
    route: "{{ item.route | default(omit) }}"
    rule: "{{ item.rule | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    to_ip: "{{ item.to_ip | default(omit) }}"
    dest: "{{ item.dest | default(omit) }}"
    to: "{{ item.to | default(omit) }}"
    to_port: "{{ item.to_port | default(omit) }}"
    port: "{{ item.port | default(omit) }}"
  loop: "{{ ufw_custom_rules }}"
  notify: 
    - Reload UFW
  when: ufw_enable