---
- name: Import tasks
  ansible.builtin.include_tasks: "{{ item }}"
  loop:
    - package.yml
    - apps.yml
    - custom_rule.yml
  when:
    - ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'
    - ufw_enable
