---
# defaults file for alloy
alloy_version: "1.3.0"

alloy_arch_mapping:
  x86_64: amd64
  aarch64: arm64
  armv7l: armhf
  i386: i386
  ppc64le: ppc64le

alloy_arch: "{{ alloy_arch_mapping[ansible_architecture] | default('amd64') }}"

alloy_binary_url: "https://github.com/grafana/alloy/releases/download/v{{ alloy_version }}/alloy-linux-{{ alloy_arch }}.zip"

alloy_service_name: "alloy"

alloy_installation_dir: "/usr/local/bin"

alloy_environment_file: "service.env"

alloy_config_dir: "/etc/alloy"

alloy_config_file: "config.alloy"

alloy_service_user: "alloy"

alloy_service_group: "alloy"

alloy_working_dir: "/var/lib/alloy"

alloy_env_file_vars: {}

# alloy_flags_extra: ''

# alloy_start_after_service: ''

alloy_config: |
  // No config provided

# Configurable user groups that the Grafana Alloy can be put in so that it can access logs.
alloy_user_groups: []

_alloy_healthcheck_endpoint: "http://localhost:12345/metrics"