---
# tasks file for keepalived
- name: Update Package Cache
  ansible.builtin.apt:
    update_cache: true
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'

- name: Install Keepalived
  ansible.builtin.package:
    name: keepalived
    state: present

- name: Add IPVS kernel module
  community.general.modprobe:
    name: ip_vs
    state: present
    persistent: true

- name: Manage keepalived.conf
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    trim_blocks: true
    lstrip_blocks: true
    owner: root
    group: root
    mode: '0644'
  notify: Restart Keepalived

- name: Manage keepalived.service
  ansible.builtin.systemd_service:
    name: keepalived
    enabled: true
    state: started
    daemon_reload: true
