---
# defaults file for ufw
ufw_enable: true
ufw_use_reject: false

ufw_default_allow_apps:
  - OpenSSH

ufw_default_deny_apps: []

# ufw_custom_rules:
#   - name: my-rule-name
#     port: 1234:2345
#     proto: tcp
#     rule: allow
ufw_custom_rules: []

ufw_enable_apps: []

ufw_disable_apps: []

ufw_deny_apps: []

ufw_reject_apps: []

# ufw_limit_apps:
#   - port: ssh
#     proto: tcp
ufw_limit_apps: []

ufw_default_app_profiles:
  - app_name: traefik
    profiles:
      - name: Traefik
        title: Web Server
        description: Allow HTTP and HTTPS traffic
        tcp_ports:
          - 80
          - 443
          - 8080
          - 9000
  - app_name: tempo
    profiles:
      - name: Tempo
        title: Telemetry Aggregator
        description: Allow tempo default port
        tcp_ports:
          - 3200
          - 9095
          - 9411
          - 14250
          - 14268
          - 4318
          - 4317
          - 55678
  - app_name: mimir
    profiles:
      - name: Mimir
        title: Metrics Aggregator
        description: Allow mimir default port
        tcp_ports:
          - 8080
  - app_name: loki
    profiles:
      - name: Loki
        title: Logging Aggregator
        description: Allow loki default port
        tcp_ports:
          - 3100
  - app_name: grafana
    profiles:
      - name: Grafana
        title: Monitoring Dashboard
        description: Allow grafana default port
        tcp_ports:
          - 3000

ufw_custom_app_profiles: []
