---
# tasks file for dnsmasq
- name: Install dnsmasq
  ansible.builtin.apt:
    name: dnsmasq
    state: present
    update_cache: true

- name: Create dnsmasq state directory
  ansible.builtin.file:
    path: /var/lib/dnsmasq/
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Manage dnsmasq configuration file
  ansible.builtin.template:
    src: config.conf.j2
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: '0644'
    trim_blocks: true
    lstrip_blocks: true
  notify:
    - Restart dnsmasq

- name: Manage dnsmasq static leases
  ansible.builtin.template:
    src: static.conf.j2
    dest: /etc/dnsmasq.d/static.conf
    owner: root
    group: root
    mode: '0644'
    trim_blocks: true
    lstrip_blocks: true
  notify:
    - Restart dnsmasq

- name: Manage dnsmasq dns records
  ansible.builtin.template:
    src: records.conf.j2
    dest: /etc/dnsmasq.d/records.conf
    owner: root
    group: root
    mode: '0644'
    trim_blocks: true
    lstrip_blocks: true
  notify:
    - Restart dnsmasq
