---
# tasks file for timezone
- name: Ensure lm-sensors is installed
  ansible.builtin.package:
    name: tzdata
    state: present

- name: Configure Timezone
  community.general.timezone:
    name: "{{ timezone_tz_name | default('UTC') }}"
    hwclock: "{{ timezone_hwclock | default('UTC') }}"
