---
# tasks file for docker
- name: Download Docker Signing Key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    checksum: sha256:1500c1f56fa9e26b9b8f42452a553675796ade0807cdce11975eb98170b3a570

- name: Add Docker Sources
  ansible.builtin.template:
    src: docker-list.j2
    dest: /etc/apt/sources.list.d/docker.list
    owner: root
    group: root
    mode: '0644'
    backup: false
  vars:
    arch: amd64 # TODO: Add support for other architectures

- name: Install Docker
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin

- name: Add Docker Daemon Config
  ansible.builtin.template:
    src: daemon.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
    backup: false
  notify:
    - restart_docker

- name: Enable Docker Systemd Service
  ansible.builtin.systemd_service:
    name: docker
    enabled: true
    state: started

- name: Add Users to docker Group
  ansible.builtin.user:
    name: "{{ docker_user }}"
    groups: docker
    append: true
  with_items: "{{ docker_extra_users }}"
  loop_control:
    loop_var: docker_user
