- name: Create traefik systemd service
  ansible.builtin.template:
    src: traefik.service.j2
    dest: "/etc/systemd/system/traefik.service"
    owner: root
    group: root
    mode: '0644'
  notify: 
    - Reload systemd