on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Run Release Please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.REPO_GITHUB_TOKEN}}
          release-type: simple
          extra-files: |
            galaxy.yml
      - name: Checkout Source
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4
      - name: Setup Python
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install Dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: |
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Build Collection
        if: ${{ steps.release.outputs.release_created }}
        run: |
          ansible-galaxy collection build
      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} ./voidrot-homelab-*.tar.gz
